# Generated by Django 2.2.19 on 2023-01-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221209_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
